export const SHORT_FINANCIAL_DISCLAIMER =
  'StockFit provides AI-generated financial insights for informational and educational purposes only. Predictions and recommendations may be inaccurate and should not be considered financial advice. Users are solely responsible for their investment decisions and financial outcomes.';

export const TERMS_SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    paragraphs: [
      'By accessing or using StockFit, users agree to comply with and be bound by these Terms & Conditions. If you do not agree with these terms, you should not use the platform.',
    ],
  },
  {
    title: '2. Nature of the Platform',
    paragraphs: [
      'StockFit is an AI-powered financial analytics and stock recommendation platform designed for educational, informational, and research purposes only.',
    ],
    lists: [
      {
        title: 'The platform provides:',
        items: [
          'AI-generated stock insights',
          'Risk-profile-based recommendations',
          'Portfolio-related analytical tools',
          'Educational financial information',
        ],
      },
      {
        title: 'StockFit does not provide:',
        items: [
          'financial advice',
          'investment advisory services',
          'brokerage services',
          'guaranteed investment outcomes',
        ],
      },
    ],
  },
  {
    title: '3. No Financial Advice',
    paragraphs: [
      'All content, predictions, recommendations, analytics, and outputs generated by StockFit are for informational purposes only.',
    ],
    lists: [
      {
        title: 'Nothing on the platform should be interpreted as:',
        items: [
          'professional financial advice',
          'investment advice',
          'legal advice',
          'tax advice',
          'trading guarantees',
        ],
      },
    ],
    closing:
      'Users should always conduct their own research and consult qualified financial professionals before making investment decisions.',
  },
  {
    title: '4. AI & Model Disclaimer',
    paragraphs: [
      'StockFit uses machine learning models, statistical methods, and AI systems to generate insights and recommendations.',
      'Financial markets are highly volatile and unpredictable. As a result:',
    ],
    lists: [
      {
        items: [
          'predictions may be inaccurate',
          'recommendations may be incomplete',
          'outputs may contain errors',
          'market conditions may rapidly change',
        ],
      },
      {
        title: 'StockFit does not guarantee:',
        items: [
          'prediction accuracy',
          'profitability',
          'future performance',
          'investment success',
        ],
      },
    ],
    closing: 'Past performance and historical analysis do not guarantee future results.',
  },
  {
    title: '5. User Responsibility',
    paragraphs: ['Users are solely responsible for:'],
    lists: [
      {
        items: [
          'their investment decisions',
          'trading activity',
          'financial outcomes',
          'portfolio management choices',
        ],
      },
    ],
    closing:
      'By using StockFit, users acknowledge that they use the platform entirely at their own risk.',
  },
  {
    title: '6. Limitation of Liability',
    paragraphs: [
      'To the maximum extent permitted by law, StockFit, its owners, developers, affiliates, contributors, and operators shall not be liable for:',
    ],
    lists: [
      {
        items: [
          'financial losses',
          'trading losses',
          'indirect damages',
          'consequential damages',
          'lost profits',
          'investment-related damages',
          'data inaccuracies',
          'service interruptions',
        ],
      },
    ],
    closing: 'arising from the use of the platform or reliance on its outputs.',
  },
  {
    title: '7. User Accounts',
    paragraphs: ['Users may be required to create an account to access certain features.', 'Users are responsible for:'],
    lists: [
      {
        items: [
          'maintaining the confidentiality of their credentials',
          'securing their account access',
          'ensuring information provided is accurate',
        ],
      },
    ],
    closing: 'StockFit reserves the right to suspend or terminate accounts that violate platform policies.',
  },
  {
    title: '8. Risk Profiling Questionnaire',
    paragraphs: ['StockFit may ask users financial preference questions such as:'],
    lists: [
      {
        items: [
          'investment amount',
          'monthly investment capacity',
          'investment preferences',
          'risk tolerance',
        ],
      },
      {
        title: 'This information is used solely to:',
        items: [
          'personalize recommendations',
          'improve user experience',
          'generate risk-profile-based insights',
        ],
      },
    ],
    closing: 'The information is not sold or shared with third parties.',
  },
  {
    title: '9. Intellectual Property',
    paragraphs: [
      'All platform content, branding, AI systems, algorithms, visuals, and software are the intellectual property of StockFit unless otherwise stated.',
      'Users may not:',
    ],
    lists: [
      {
        items: [
          'copy platform code',
          'reverse engineer systems',
          'redistribute proprietary content',
          'exploit platform materials commercially without permission',
        ],
      },
    ],
  },
  {
    title: '10. Modifications to the Service',
    paragraphs: ['StockFit reserves the right to:'],
    lists: [
      {
        items: ['modify features', 'update algorithms', 'suspend services', 'discontinue parts of the platform'],
      },
    ],
    closing: 'without prior notice.',
  },
  {
    title: '11. Changes to Terms',
    paragraphs: [
      'StockFit may update these Terms & Conditions at any time. Continued use of the platform after updates constitutes acceptance of the revised terms.',
    ],
  },
];

export const PRIVACY_SECTIONS = [
  {
    title: '1. Information We Collect',
    lists: [
      {
        title: 'Account Information',
        intro: 'When users register, we may collect:',
        items: ['full name', 'email address', 'encrypted password credentials'],
      },
      {
        title: 'Questionnaire Information',
        intro: 'We may collect information related to:',
        items: [
          'investment capacity',
          'monthly investment budget',
          'risk tolerance',
          'financial preferences',
        ],
      },
      {
        intro: 'This information is used strictly for:',
        items: [
          'risk profiling',
          'personalized recommendations',
          'improving recommendation quality',
        ],
      },
    ],
  },
  {
    title: '2. Cookies & Authentication',
    paragraphs: ['StockFit uses cookies and authentication tokens to:'],
    lists: [
      {
        items: [
          'keep users logged in',
          'improve platform experience',
          'maintain secure sessions',
          'remember user preferences',
        ],
      },
    ],
    closing: 'These cookies are not used for selling personal data or third-party advertising.',
  },
  {
    title: '3. How We Use Data',
    paragraphs: ['Collected information may be used to:'],
    lists: [
      {
        items: [
          'provide personalized recommendations',
          'improve platform functionality',
          'enhance AI model performance',
          'improve user experience',
          'maintain account security',
          'analyze platform usage trends',
        ],
      },
    ],
    closing:
      'In the future, anonymized and aggregated user data may be used to improve and train machine learning models. Personal data will not be sold to third parties.',
  },
  {
    title: '4. Data Storage & Security',
    paragraphs: ['User data is securely stored using Supabase infrastructure and security systems.', 'We implement reasonable technical and organizational measures to protect user data from:'],
    lists: [
      {
        items: ['unauthorized access', 'misuse', 'disclosure', 'alteration', 'destruction'],
      },
    ],
    closing: 'However, no online platform can guarantee absolute security.',
  },
  {
    title: '5. Third-Party Services',
    paragraphs: ['StockFit may use trusted third-party services for:'],
    lists: [
      {
        items: ['hosting', 'authentication', 'analytics', 'database infrastructure'],
      },
    ],
    closing: 'These providers only process data necessary for platform functionality.',
  },
  {
    title: '6. Data Sharing',
    paragraphs: ['StockFit does not:'],
    lists: [
      {
        items: ['sell user data', 'rent user data', 'share personal data with advertisers'],
      },
    ],
    closing: 'User information is only accessed internally for operational and recommendation-related purposes.',
  },
  {
    title: '7. User Rights',
    paragraphs: ['Users may request to:'],
    lists: [
      {
        items: [
          'access their data',
          'update account information',
          'delete their account',
          'request removal of stored data',
        ],
      },
    ],
    closing: 'Requests may be submitted through platform support channels.',
  },
  {
    title: '8. Data Retention',
    paragraphs: ['We retain user information only as long as necessary for:'],
    lists: [
      {
        items: [
          'providing services',
          'maintaining platform functionality',
          'improving recommendation systems',
          'complying with legal obligations',
        ],
      },
    ],
  },
  {
    title: '9. Children\'s Privacy',
    paragraphs: ['StockFit is not intended for individuals under the age of 18.'],
  },
  {
    title: '10. Policy Updates',
    paragraphs: [
      'This Privacy Policy may be updated periodically. Continued use of the platform after updates indicates acceptance of the revised policy.',
    ],
  },
];
